### ISSUE TITLE
2.2.1 release build failure

### ISSUE THREAD

**Issue by chenrui333** [iamarkadyt/aws-auth#10]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
$ aws-auth login
/opt/homebrew/Cellar/aws-auth/2.2.1/libexec/lib/node_modules/@iamarkadyt/aws-auth/src/helpers/aws.js:12
    constructAwsConfig,
    ^

ReferenceError: constructAwsConfig is not defined
    at Object.<anonymous> (/opt/homebrew/Cellar/aws-auth/2.2.1/libexec/lib/node_modules/@iamarkadyt/aws-auth/src/helpers/aws.js:12:5)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/opt/homebrew/Cellar/aws-auth/2.2.1/libexec/lib/node_modules/@iamarkadyt/aws-auth/src/helpers/index.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)

Node.js v21.7.
```

</details>

relates to Homebrew/homebrew-core#168082

**Comment by chenrui333** [comment]
2.2.3 release works for me well. closing the issue now.
